# Generated by Django 4.2.16 on 2024-10-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lab4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('area1', models.FloatField()),
                ('area2', models.FloatField()),
                ('area3', models.FloatField()),
                ('a1', models.FloatField()),
                ('b1', models.FloatField()),
                ('n1', models.PositiveIntegerField()),
                ('func1', models.CharField(max_length=255)),
                ('a2', models.FloatField()),
                ('b2', models.FloatField()),
                ('n2', models.PositiveIntegerField()),
                ('func2', models.CharField(max_length=255)),
                ('a3', models.FloatField()),
                ('b3', models.FloatField()),
                ('n3', models.PositiveIntegerField()),
                ('func3', models.CharField(max_length=255)),
            ],
        ),
    ]
