# Generated by Django 4.2.16 on 2024-11-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lab6', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab6',
            name='x1_res',
        ),
        migrations.RemoveField(
            model_name='lab6',
            name='x2_res',
        ),
        migrations.RemoveField(
            model_name='lab6',
            name='y1_res',
        ),
        migrations.RemoveField(
            model_name='lab6',
            name='y2_res',
        ),
    ]
